# Generated by Django 4.0 on 2021-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_enr', models.IntegerField(default=0)),
                ('date_declaration', models.DateTimeField(auto_now=True)),
                ('num_cit', models.IntegerField()),
                ('specialite', models.CharField(max_length=50)),
                ('object', models.TextField(max_length=1000)),
                ('finish', models.BinaryField(default=False)),
                ('code_req', models.CharField(max_length=250)),
                ('num_domaine', models.IntegerField()),
                ('num_com', models.IntegerField()),
                ('agent', models.CharField(max_length=50)),
            ],
        ),
    ]
