# Generated by Django 4.0 on 2021-12-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitions',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
