# Generated by Django 4.0 on 2021-12-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_alter_petitions_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitions',
            name='specialite',
            field=models.CharField(max_length=500),
        ),
    ]
