# Generated by Django 4.0 on 2021-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL Time', 'Full time'), ('Part time', 'Part time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
